version: '3.8'

services:
  db:
    image: mysql:8.1
    container_name: bookstack_db
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: bookstack
      MYSQL_USER: bookstack_user
      MYSQL_PASSWORD: rxhhyundD(254J#!
    volumes:
      - ./dev/docker/init.db:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    networks:
      - bs2_network

  web:
    image: php:8.1-apache
    container_name: bookstack_web
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
      - ./apache-config.conf:/etc/apache2/sites-available/000-default.conf
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
      - bs2_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: S*26)Q$H3Dd1Dmp
    depends_on:
      - db
    networks:
      - bs2_network
      
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      APP_URL: http://172.16.1.146
      APP_KEY: YOUR_GEN_KEY
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: bookstack
      DB_USERNAME: bookstack_user
      DB_PASSWORD: rxhhyundD(254J#!
    volumes:
      - ./:/var/www/html
    networks:
      - bs2_network
    depends_on:
      - db 
   
  reverse-proxy:
    image: nginx:latest
    container_name: reverse_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    depends_on:
      - app
    networks:
      - bs2_network

volumes:
  db:

networks:
  bs2_network:
    driver: bridge

Corrected version: 
version: '3.8'

services:
  db:
    image: mysql:8.1
    container_name: bookstack_db
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: bookstack
      MYSQL_USER: bookstack_user
      MYSQL_PASSWORD: 'rxhhyundD(254J#!'
    volumes:
      - ./dev/docker7init.db:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    networks:
      - bs2_network

  web:
    image: php:8.1-apache
    container_name: bookstack_web
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
      - ./apache-config.conf:/etc/apache2/sites-available/000-default.conf
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
      - bs2_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 'S*26)Q$H3Dd1Dmp'
    depends_on:
      - db
    networks:
      - bs2_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      APP_URL: https://yourdomain.com
      APP_KEY: 'YOUR_GEN_KEY'
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: bookstack
      DB_USERNAME: bookstack_user
      DB_PASSWORD: 'rxhhyundD(254J#!'
      LDAP_ENABLED: 'true'
      LDAP_HOST: 'your_ldap_host'
      LDAP_PORT: 389
      LDAP_BASE_DN: 'dc=example,dc=com'
      LDAP_USERNAME: 'cn=admin,dc=example,dc=com'
      LDAP_PASSWORD: 'your_ldap_password'
    volumes:
      - ./:/var/www/html
    networks:
      - bs2_network
    depends_on:
      - db 

  reverse-proxy:
    image: nginx:latest
    container_name: reverse_proxy
    restart: always
    ports:
      - "80:81"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./certs:/etc/nginx/certs
    depends_on:
      - app
    networks:
      - bs2_network

volumes:
  db:

networks:
  bs2_network:
    driver: bridge
